export default constants = {
    audio: 'audio',
    playList: 'playList',
    currentPlayList: 'currentPlayList',
    granted: 'granted',
    denied: 'denied',
    window: 'window',
    PREV: 'PREV',
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    NEXT: 'NEXT',
    AudioList: 'Audio List',
    AudioPlayer: 'Audio Player',
    PlayList: 'Play List',
    PlayListHome: 'Play List Home',
    PlayListDetail: 'Play List Detail',
    allow: 'Allow',
    cancel: 'Cancel',
    permissionRequired: 'Permission Required',
    pemissionDescription: 'This app needs permission to read audio files.',
    musicAlreadyAdded: 'Music Already Added to Play List'
};